baseURL: https://memos.moe/
languageCode: en-US
title: Moe Memos
theme: PaperMod
params:
  profileMode:
    enabled: true
    title: Moe Memos
    subTitle: |
      An app to help you capture thoughts and ideas, works with [✍️memos](https://github.com/usememos/memos).   
      Availabile on iPhone and iPad. Public beta on Android.
    imageUrl: /memos.png
    imageWidth: 68
    imageHeight: 68
  hideFooter: true
  assets:
    favicon: "/favicon.png"
  socialIcons:
  - name: GitHub
    url: /open-source/
  - name: Twitter
    url: https://twitter.com/MoeMemos
  - name: Email
    url: mailto:memos@memos.moe