baseURL: https://moodlight.icebear.tech/
languageCode: en-US
title: MoodLight: Create the Atmosphere You Want | Best Mood Lighting Solutions 
theme: PaperMod
params:
  profileMode:
    enabled: true
    title: MoodLight: Create the Atmosphere You Want | Best Mood Lighting Solutions 
    subTitle: |
      Illuminate your world with MoodLight, the leading provider of mood lighting solutions. Let us help you set the perfect ambiance for any occasion. Browse our collection of innovative and high-quality mood lighting products now.
    imageUrl: /moodlight.png
    imageWidth: 68
    imageHeight: 68
  hideFooter: true
  assets:
    favicon: "/favicon.ico"
  socialIcons:
  # - name: GitHub
  #   url: /open-source/
  # - name: Mastodon
  #   url: https://fosstodon.org/@moememos
  - name: Email
    url: mailto:hi@icebear.tech
